# Warning:
#
# If you configure a lot of the possible sensors etc. it could be that you run
# out of memory (on esp8266). If you configure nearly all sensors etc. you run
# in a stack-size issue. In this case you have to increase stack size!
#
#  https://github.com/esphome/issues/issues/855

substitutions:
  name: pipsolar

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://chipsi/esphome-pipsolar-voltronic@easun-sv-iv
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  baud_rate: 0

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  id: uart0
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO3

pipsolar:
  uart_id: uart0
  id: inverter0

# Example configuration entry
text_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    device_mode:
      id: inverter0_device_mode
      name: inverter0_device_mode
    last_qpigs:
      id: inverter0_last_qpigs
      name: inverter0_last_qpigs
    last_qpiri:
      id: inverter0_last_qpiri
      name: inverter0_last_qpiri

# Example configuration entry
sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    ac_output_apparent_power:
      id: inverter0_ac_output_apparent_power
      name: inverter0_ac_output_apparent_power
      accuracy_decimals: 0
    ac_output_active_power:
      id: inverter0_ac_output_active_power
      name: inverter0_ac_output_active_power
      accuracy_decimals: 0
    output_load_percent:
      id: inverter0_output_load_percent
      name: inverter0_output_load_percent
    pv_charging_power:
      id: inverter0_pv_charging_power
      name: inverter0_pv_charging_power
      accuracy_decimals: 0
    pv_input_current_for_battery:
      id: inverter0_pv_input_current_for_battery
      name: inverter0_pv_input_current_for_battery
    pv_input_voltage:
      id: inverter0_pv_input_voltage
      name: inverter0_pv_input_voltage
    battery_voltage:
      id: inverter0_battery_voltage
      name: inverter0_battery_voltage
    battery_charging_current:
      id: inverter0_battery_charging_current
      name: inverter0_battery_charging_current
    battery_discharge_current:
      id: inverter0_battery_discharge_current
      name: inverter0_battery_discharge_current
    bus_voltage:
      id: inverter0_bus_voltage
      name: inverter0_bus_voltage
    battery_bulk_voltage:
      id: inverter0_battery_bulk_voltage
      name: inverter0_battery_bulk_voltage
    battery_float_voltage:
      id: inverter0_battery_float_voltage
      name: inverter0_battery_float_voltage
    inverter_heat_sink_temperature:
      id: inverter0_inverter_heat_sink_temperature
      name: "Měnič 0-teplota chladiče"
      accuracy_decimals: 0

  - platform: total_daily_energy
    name: "Inverter 0 - total energy"
    id: inverter0_ac_output_energy_meter
    power_id: inverter0_ac_output_active_power
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 0.001

  - platform: template
    name: "Inverter 0 - PV power"
    id: inverter0_pv_charging_power_complete
    icon: mdi:flash
    unit_of_measurement: "W"
    device_class: "energy"
    accuracy_decimals: 0

  - platform: total_daily_energy
    name: "Inverter 0 - PV daily energy"
    id: inverter0_pv_energy_meter
    power_id: inverter0_pv_charging_power
    icon: mdi:lightning-bolt
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 0.001

# Example configuration entry
switch:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority_utility:
      name: inverter0_output_source_priority_utility
    output_source_priority_solar:
      name: inverter0_output_source_priority_solar
    output_source_priority_battery:
      name: inverter0_output_source_priority_battery
    input_voltage_range:
      name: inverter0_input_voltage_range
    pv_ok_condition_for_parallel:
      name: inverter0_pv_ok_condition_for_parallel
    pv_power_balance:
      name: inverter0_pv_power_balance

# Example configuration entry
binary_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    add_sbu_priority_version:
      id: inverter0_add_sbu_priority_version
      name: inverter0_add_sbu_priority_version
    configuration_status:
      id: inverter0_configuration_status
      name: inverter0_configuration_status
    switch_on:
      id: inverter0_switch_on
      name: inverter0_switch_on

# Example configuration entry
output:
  - platform: pipsolar
    pipsolar_id: inverter0
    battery_recharge_voltage:
      id: inverter0_battery_recharge_voltage_out

select:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority:
      id: inverter0_output_source_priority_select
      name: inverter0_output_source_priority_select
      optionsmap:
        "Utility first": "POP00"
        "Solar only": "POP01"
        "Solar Battery Utility": "POP02"
      statusmap:
        "0": "Utility first"
        "1": "Solar only"
        "2": "Solar Battery Utility"
